services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    environment:
      - WEBPASSWORD=${WEBPASSWORD}
    volumes:
      - "./etc/pihole:/etc/pihole"
      - "./etc/dnsmasq.d:/etc/dnsmasq.d"
    networks:
      - pihole
    restart: unless-stopped

networks:
  pihole:
    name: pihole
